config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :stories
  resources :users, only: :show

  namespace :api do
    resources :users, only: :show
    resources :stories, only: [:create, :update, :destroy]
  end

  root 'stories#index'
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :user

  validates :title, :body, :user_id, presence: true

  scope :published, -> { where.not(published_at: nil) }


  def self.new_draft_for(user)
    post = self.new(user: user)
    post.save_draft
    post
  end

  def save_draft
    self.published_at = nil
    save(validate: false)
  end

  def published?
    published_at.present?
  end

  def publish
    self.published_at = Time.zone.now
    save
  end

  def unpublish
    self.published_at = nil
  end
end

app/controllers/api/stories_controller.rb
class Api::StoriesController < ApplicationController
  before_action :authenticate_user!

  def update
    @story = current_user.stories.find(params[:id])
    @story.assign_attributes(story_params)

    if @story.published?
      @story.save
    else
      @story.save_draft
    end
  end

  private

  def story_params
    params.require(:story).permit(:title, :body, :picture)
  end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :authorize_user, only: [:edit, :update, :destroy]

  layout "editor", only: [:new, :edit, :create, :update]

  def index
    @stories = Story.published
  end

  def show
  end

  def new
    @story = Story.new_draft_for(current_user)
  end

  def create
    @story = current_user.stories.build(story_params)
    if @story.publish
      redirect_to root_path, notice: "Successfully published the post!"
    else
      @story.unpublish
      flash.now[:alert] = "Could not update the post, Please try again"
      render :new
    end
  end

  def edit
  end

  def update
    @story.assign_attributes(story_params)
    if @story.publish
      redirect_to root_path, notice: "Successfully published the post!"
    else
      @story.unpublish
      flash.now[:alert] = "Could not update the post, Please try again"
      render :edit
    end
  end

  def destroy
    @story.destroy
    redirect_to root_url, notice: "Successfully deleted the post"
  end

  # TODO: ideally move this to a separate controller?
  def create_and_edit
    #@story = current_user.posts.build(post_params)
    #@story.save_as_draft
   # redirect_to edit_story_url(@story)
  end

  private

    def story_params
      params.require(:story).permit(:title, :body, :picture)
    end

    def authorize_user
      begin
        @story = current_user.stories.find(params[:id])
      rescue
        redirect_to root_url
      end
    end
end

app/helpers/stories_helper.rb
module StoriesHelper
  def story_length_in_minutes(body)
    min = body.split(" ").size / 250
    if min == 0
      'less than a minute read'
    else
      "#{min} min read"
    end
  end
end

app/views/stories/_form.html.haml
= form_for story, html: { multipart: true, class: "editor-form", data: { page: 'main-editor' }, autocomplete: "off" } do |f|
  %label.picture_upload
    = f.file_field :picture
    %i.fa.fa-camera
  .file-upload-previewer.hidden
    %img#image_preview{:src => ""}/
  - if story.picture?
    #existing-img-previewer.existing-img-previewer
      = image_tag story.picture.url(:thumb)
  .form-group
    = f.text_field :title, class: 'editor-title', placeholder: 'Title', autofocus: true, data: { behavior: "autosave" }, onfocus: "this.value = this.value;"
  .form-group
    = f.text_area :body, class: 'medium-editable', data: { behavior: "autosave" }

app/views/stories/_story.html.haml
.post-panel
  = render partial: 'story_metadata', locals: { story: story }
  .main-body
    %h3.post-title= link_to story.title, story
    .post-body= truncate(story.body, length: 140, separator: ' ', escape: false)
    = link_to "Read more", story, class: 'read-more'

app/views/stories/_story_metadata.html.haml
.post-metadata
  = avatar_for story.user, size: 40
  .post-info
    = react_component("PopoverLink", { user_id: story.user_id, url: user_path(story.user), children: story.user.username })
    %small
      = time_ago_in_words(story.created_at)
      ago #{story_length_in_minutes(story.body)}

app/views/stories/edit.html.haml
%h1 Editing story

= render 'form'

= link_to 'Show', @story
\|
= link_to 'Back', stories_path

app/views/stories/index.html.haml
.col-md-6.col-md-offset-1.dashboard-main-content
  .posts-wrapper{"data-behavior" => "endless-scroll"}
    = render @stories

app/views/stories/new.html.haml
%div
  .col-xs-10.col-sm-10.col-md-6.col-md-offset-3.col-sm-offset-1.col-xs-offset-1
    .post-metadata
      = avatar_for(current_user, size: 40)
      .post-info
        = link_to current_user.username, current_user
        %br/
        %small New Post
    = render 'form', story: @story

app/views/stories/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_story_path(@story)
\|
= link_to 'Back', stories_path