config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :stories
  resources :users, only: :show

  namespace :api do
    resources :users, only: :show
    resources :stories, only: [:create, :update, :destroy]
  end

  root 'stories#index'
end

app/views/layouts/_avatar_dropdown.haml
%li.account
  %a.avatar-wrapper.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :role => "button"}
    = avatar_for(current_user, size: 40)
  %ul.dropdown-menu.nav-dropdown
    %span.dropdown-arrow-top
    %span.dropdown-arrow-bottom
    %li.nd-main= link_to "New story", new_story_path
    %li.nd-main= link_to "Drafts and stories", "#"
    %li.divider{:role => "separator"}
    %li.nd-sub= link_to "Profile", "#"
    %li.nd-sub= link_to "Sign out", destroy_user_session_path, method: :delete

app/views/layouts/_editor_header.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .container-fluid.col-md-10.col-md-offset-1
    .navbar-header
      = link_to root_path, class: "navbar-brand", id: "logo" do
        = image_tag('logo.png', height: 40, alt: "Stories")
    %ul.nav.navbar-nav.filter-links
      %li
        %a{"data-behavior" => "editor-message", :href => "#"}
    .collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li.publish-button
          %button.button.green-border-button.pull-right{"data-behavior" => "publish-button"} Publish
        = render 'layouts/avatar_dropdown'

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default.navbar-fixed-top{"data-behavior" => "animated-navbar"}
  .container-fluid.col-md-10.col-md-offset-1
    .navbar-header
      = link_to root_path, class: "navbar-brand", id: "logo" do
        = image_tag('logo.png', height: 40, alt: "Stories")
    %ul.nav.navbar-nav.filter-links
      %li
        = nav_link_to "Staff pick", root_path
    .folding-nav
      %ul.nav.navbar-nav.navbar-right
        %li.main-searchbar
        - if user_signed_in?
          %li.new-post-button= link_to "Write a story", new_story_path, class: "button"
          = render 'layouts/avatar_dropdown'
        - else
          %li.new-post-button
            = link_to "Write a story", new_story_path, data: { turbolinks: 'false' },  class: "button"
          %li.sign-in-button
            = link_to "Sign in / Sign up", new_user_session_path, class: 'button green-border-button', data: { behavior: 'trigger-overlay' }

app/views/layouts/_overlay.html.haml
.overlay.overlay-hugeinc{"data-behavior" => "overlay"}
  %button.overlay-close{"data-behavior" => "close-overlay", :type => "button"}
    %span.glyphicon.glyphicon-remove
  %nav
    %h2.grayed-heading.center Sign in or create an account
    %ul.omniauth-button-group
      %li.omniauth-button
        = link_to user_facebook_omniauth_authorize_path, class: 'button facebook' do
          = icon('facebook-official')
          Sign in with Facebook
      %li.omniauth-button.google
        = link_to user_google_oauth2_omniauth_authorize_path, class: 'button google' do
          = icon('google')
          Sign in with Google
      %li.omniauth-button.twitter
        = link_to user_twitter_omniauth_authorize_path, class: 'button twitter' do
          = icon('twitter')
          Sign in with Twitter
      %li
        = link_to "Sign in or Sign up with email", new_user_session_path, class: "signin-signup-link"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Thinker
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body{:class => "#{controller.controller_name} #{controller.action_name}"}
    = render 'layouts/overlay' unless user_signed_in?
    = render 'layouts/header'

    .progress-bar{"data-behavior" => "progress-bar"}

    .container-fluid.main-container
      = yield

  :javascript
    window.userSignedIn = #{user_signed_in?};

app/views/layouts/editor.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Stories
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = favicon_link_tag 'favicon.png', type: 'image/png'
    = favicon_link_tag 'stories-icon-apple-touch-180x180.png', rel: 'apple-touch-icon', type: 'image/png'
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
  %body{:class => "#{controller.controller_name} #{controller.action_name}"}
    = render 'layouts/editor_header'
    //= render 'layouts/alert_messages'
    .progress-bar{"data-behavior" => "progress-bar"}
    .container-fluid
      = yield